### ISSUE TITLE
Pytest Parallel Exectuion

### ISSUE THREAD

**Issue by abubakarafzal** [nirtal85/Selenium-Python-Example#332]
**Pytest Xdist Parallel Support**
Although this framework is perfectly organized and developed but somehow using this boilerplate parallel execution should be integrated

**Issue With Pytest xdist in selenium grid**
i was executing the parallel execution in selenium grid but facing somehow sometime this issue might be due to use of pytest-teststart method which is in conftest.py

                                                                                                                                                                                        5% ▌         ```
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E                                      ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
INTERNALERROR> E                 raise exception.with_traceback(exception.__traceback__)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/xdist/remote.py", line 157, in pytest_runtestloop
INTERNALERROR> E                 self.run_one_test()
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/xdist/remote.py", line 174, in run_one_test
INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 181, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_result.py", line 99, in get_result
INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/runner.py", line 114, in pytest_runtest_protocol
INTERNALERROR> E                 runtestprotocol(item, nextitem=nextitem)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/runner.py", line 134, in runtestprotocol
INTERNALERROR> E                 reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
INTERNALERROR> E                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/runner.py", line 228, in call_and_report
INTERNALERROR> E                 hook.pytest_exception_interact(node=item, call=call, report=report)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
INTERNALERROR> E                 raise exception.with_traceback(exception.__traceback__)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/tests/conftest.py", line 172, in pytest_exception_interact
INTERNALERROR> E                 window_count = len(driver.window_handles)
INTERNALERROR> E                                    ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 491, in window_handles
INTERNALERROR> E                 return self.execute(Command.W3C_GET_WINDOW_HANDLES)["value"]
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
INTERNALERROR> E                 self.error_handler.check_response(response)
INTERNALERROR> E               File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
INTERNALERROR> E                 raise exception_class(message, screen, stacktrace)
INTERNALERROR> E             selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: 948474acfabe0f1e83947989db81be5d
INTERNALERROR> E             Build info: version: '4.14.1', revision: '03f8ede370'
INTERNALERROR> E             System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.4.16-linuxkit', java.version: '11.0.20.1'
INTERNALERROR> E             Driver info: driver.version: unknown
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> venvS2/lib/python3.12/site-packages/xdist/dsession.py:200: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 138, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/xdist/dsession.py", line 123, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/xdist/dsession.py", line 148, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvS2/lib/python3.12/site-packages/xdist/dsession.py", line 187, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('tests/test_Annotation.py::TestsAnnotationFirstTestCase::test_Annotation_First_TestCase', <WorkerController gw1>)
INTERNALERROR> assert not 'tests/test_Annotation.py::TestsAnnotationFirstTestCase::test_Annotation_First_TestCase'

```

**Comment by abubakarafzal** [comment]
@nirtal85
